name: activitygo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  fl_chart: ^0.50.5
  emoji_picker_flutter: ^1.1.2
  flutter_heatmap_calendar: ^1.0.4
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  duration_picker: ^1.1.0+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  page_transition: ^2.0.5
  animated_splash_screen: ^1.2.0
  flutter_native_splash: ^2.2.1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_charts: ^20.1.57
  jiffy: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/appIcon.png
  color_dark: "#000000"
  image_dark: assets/appIcon.png

  android_12:
    image: assets/appIcon.png
    icon_background_color: "#ffffff"
    image_dark: assets/appIcon.png
    icon_background_color_dark: "#000000"

  web: false

flutter_icons:
  android: true
  image_path: "assets/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/appIcon.png